### ISSUE TITLE
[suggestion] add the Vue2 and Vue3 version as the bottomline benchmark

### ISSUE THREAD

**Issue by Stvchm9703** [yangmingshan/mp-framework-benchmark#2]
雖然我不知道微信小程序的生態，但作為Vue的用家想知道Vue mini，Vue2 和 Vue 3 之間的差距，好作底線參考

**Comment by yangmingshan** [comment]
你是想对比 Vue 2 跟 Vue 3，还是 Vue Mini 与 Vue?

如果是前者，这没有太大意义，你应该尽可能用 Vue 3。如果是后者，它们平台不同无法直接对比。
