### ISSUE TITLE
Taro + VirtualList 会不会性能好一些？

### ISSUE THREAD

**Issue by naico-wang** [yangmingshan/mp-framework-benchmark#3]

**Comment by yangmingshan** [comment]
不确定，VirtualList 也有自己的问题，例如快速滚动时白屏。这只是一个基准测试，不用 VirtualList 是合理的。

**Comment by naico-wang** [comment]
明白了，很详尽。晚上使用一下，👍

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Yang Mingshan ***@***.***>
发送时间: Wednesday, July 31, 2024 6:10:44 PM
收件人: yangmingshan/mp-framework-benchmark ***@***.***>
抄送: Naico Wang ***@***.***>; Author ***@***.***>
主题: Re: [yangmingshan/mp-framework-benchmark] Taro + VirtualList 会不会性能好一些？ (Issue #3)


不确定，VirtualList 也有自己的问题，例如快速滚动时白屏。这只是一个基准测试，不用 VirtualList 是合理的。
